### ISSUE TITLE
Can I request a wee change to submission method?

### ISSUE THREAD

**Issue by DavidFarrell** [falconhoof/Game-Jam-2012-Server#3]
So, you told me how to submit: 

curl -d "explosions=2&deaths=37&fucks_given=99" http://falconhoof.heroku.com/api/v1/stats/

I don't have a curl command in AS3 - but I can submit to a URL.

Can you make it so that this would work?

http://falconhoof.heroku.com/api/v1/stats/someurl.extension?explosions=2&deaths=37&fucks_given=99

**Comment by leereilly** [comment]
I can, but you should be able to. Trying googling relevant thing + "http" + "post" + "request"...
