### ISSUE TITLE
Embed code to allow play on our heroku site

### ISSUE THREAD

**Issue by DavidFarrell** [falconhoof/Game-Jam-2012-Server#7]
You should be able to copy / paste this in any page. (code not showing - and I can't see how to attach a file?) so I have escape char'd the text to make it visible in the box. But that just made it go mental.

hahaha

&lt;object classid=&quot;clsid:d27cdb6e-ae6d-11cf-96b8-444553540000&quot; width=&quot;1280&quot; height=&quot;720&quot; id=&quot;movie_name&quot; align=&quot;middle&quot;&gt;
    &lt;param name=&quot;movie&quot; value=&quot;http://www.gameologist.com/portfolio/ggj2012/past-life/Main.swf\&quot;/&gt;
    &lt;!--[if !IE]&gt;--&gt;
    &lt;object type=&quot;application/x-shockwave-flash&quot; data=&quot;http://www.gameologist.com/portfolio/ggj2012/past-life/Main.swf\&quot; width=&quot;1280&quot; height=&quot;720&quot;&gt;
        &lt;param name=&quot;movie&quot; value=&quot;http://www.gameologist.com/portfolio/ggj2012/past-life/Main.swf\&quot;/&gt;
    &lt;!--&lt;![endif]--&gt;
        &lt;a href=&quot;http://www.adobe.com/go/getflash\&quot;&gt;
            &lt;img src=&quot;http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\&quot; alt=&quot;Get Adobe Flash player&quot;/&gt;
        &lt;/a&gt;
    &lt;!--[if !IE]&gt;--&gt;
    &lt;/object&gt;
    &lt;!--&lt;![endif]--&gt;
&lt;/object&gt;

**Comment by leereilly** [comment]
You can format code with [Markdown](http://github.github.com/github-flavored-markdown/).

```
10 PRINT "TAXI FOR MONGO"
20 GOTO 10
```

1280 pixels wide messes up the layout; this is the best I can do in the short-term: http://falconhoof.heroku.com/play

**Comment by DavidFarrell** [comment]
durrrrrr

where's ma slippurs

On 30 January 2012 22:56, Lee Reilly <
reply@reply.github.com
